language: python

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libopenobex1-dev
install:
    - pip install pybluez
    - pip install --allow-all-external --allow-unverified lightblue lightblue

script: nosetests

notification:
    email:
        - eliasj@student.chalmers.se
